#!/bin/sh
#
# Copyright 2015 the original author or authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced functionality shells and target
#       temporary workaround for OSes lacking /bin/bash support:
#
#           #!/bin/sh (or #!/usr/bin/env sh)
#
#           exec env JAVA_HOME=/opt/java/openjdk "$SHELL" "$0" "$@"
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

while [ -h "$app_path" ] ; do ls=`ls -ld "$app_path"`; link=`expr "$ls" : '.*-> \(.*\)$'`; if expr "$link" : '/.*' > /dev/null; then app_path="$link"; else app_path=`dirname "$app_path"`"/$link"; fi; done
APP_HOME=$(dirname "$app_path")/..
APP_HOME=$(cd "$APP_HOME" && pwd)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum
warn () {
    echo "$*"
} >&2
die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS=$(uname -s)
case "$OS" in
    MINGW* | MSYS* | CYGWIN*) ;;
    *)
        MAX_FD_LIMIT=$(ulimit -H -n)
        if [ $? -eq 0 ] ; then
            if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ] ; then
                MAX_FD="$MAX_FD_LIMIT"
            fi
            ulimit -n $MAX_FD
            if [ $? -ne 0 ] ; then
                warn "Could not set maximum file descriptor limit: $MAX_FD"
            fi
        else
            warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
        fi
        ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the java command to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

exec "$JAVACMD" \
  $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
